<a href="https://colab.research.google.com/github/YuriiBlack/Git/blob/master/ML_Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [161]:
import numpy as np
l = np.array([1,2,3,4])
print("Create a matrix with numpy")
print(l)
print("Create a matrix with other method")
k = np.zeros( (3,4) )
print(k)
print("Multiplate with method with numpy")
print(k.dot(l))

Create a matrix with numpy
[1 2 3 4]
Create a matrix with other method
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Multiplate with method with numpy
[0. 0. 0.]


In [162]:
import time 
A=[[1,2,3],[4,5,6],[7,8,9]]
B=[[1,2,3],[4,5,6],[7,8,9]]
matrix=[]

def multiplicationLineColumn(line,column):
    try:
        sizeLine=len(line)
        sizeColumn=len(column)
        if(sizeLine!=sizeColumn):
            raise ValueError("Exception")
        res = sum([line[i] * column[i] for i in range(sizeLine)])
        return res
    except ValueError:
        print("sould have the same len line & column")

def  getColumn(matrix,numColumn):
    size=len(matrix)
    column= [matrix[i][numColumn] for i in range(size)]
    return column

def getLine(matrix,numLine):
    line = matrix[numLine]
    return line
timeof1 = time.time()
for i in range(len(A)):
    matrix.append([])
    for j in range(len(B)):
        matrix[i].append(multiplicationLineColumn(getLine(A,i),getColumn(B,j)))
print("Matrix by Matrix without numpy:")
print(matrix)
print("Time is:")
print(time.time()-timeof1)

Matrix by Matrix without numpy:
[[30, 36, 42], [66, 81, 96], [102, 126, 150]]
Time is:
0.00041365623474121094


In [163]:
import numpy as np
a = np.array([[ 1, 2 ,3], 
                  [ 4, 5 ,6], 
                  [ 7, 8 ,9]])

b = np.array([[ 1, 2 ,3], 
                  [ 4, 5 ,6], 
                  [ 7, 8 ,9]])

timeof2 = time.time()
print("Matrix by Matrix wuth numpy:")
print(a.dot(b))
print("Tims is:")
print(time.time()-timeof2)


Matrix by Matrix wuth numpy:
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
Tims is:
0.0036454200744628906


In [164]:
def vectorbyVector(vectorA, vectorB, lenght):
    scalar = 0
    for i in range(lenght):
        scalar = scalar + vectorA[i]*vectorB[i]
    return scalar

In [165]:
timeof3 = time.time()
print("Time is")
print(time.time()-timeof3)
print("Vector by Vactor without numpy:")
vectorbyVector(vectoeA,vectorB,200)


Time is
0.0003845691680908203
Vector by Vactor without numpy:


53.572024291820796

In [166]:
timeof4 = time.time()
print("Time is :")
print(time.time()-timeof4)
print("Vector by Vector with numpy:")
print(vectoeA.dot(vectorB))


Time is :
0.0021543502807617188
Vector by Vector with numpy:
53.57202429182078


In [167]:
a1 = np.array([[ 1, 2 ,3], 
                  [ 4, 5 ,6], 
                  [ 7, 8 ,9]])

list1 = [1, 2, 3]
vector1 = np.array(list1)

print("Matrix by Vector:")
print(a1.dot(vector1))
print("Vector by Metrix:")
print(vector1.dot(a1))

Matrix by Vector:
[14 32 50]
Vector by Metrix:
[30 36 42]
